export const plantillaTableData = [
    {
        id: 1,
        itemNo: 'OSEC-DOSTTB-EXA3-1-2019',
        position: 'Executive Assistant III',
        office: 'OSEC-A',
        status: 'Contructual',
    },
    {
        id: 2,
        itemNo: 'OSEC-DOSTTB-EXA3-1-2019',
        position: 'Executive Assistant III',
        office: 'OSEC-A',
        status: 'Contructual',
    },
    {
        id: 3,
        itemNo: 'OSEC-DOSTTB-EXA3-1-2019',
        position: 'Executive Assistant III',
        office: 'OSEC-A',
        status: 'Contructual',
    },
    {
        id: 4,
        itemNo: 'OSEC-DOSTTB-EXA3-1-2019',
        position: 'Executive Assistant III',
        office: 'OSEC-A',
        status: 'Contructual',
    },
    {
        id: 5,
        itemNo: 'OSEC-DOSTTB-EXA3-1-2019',
        position: 'Executive Assistant III',
        office: 'OSEC-A',
        status: 'Contructual',
    },
    {
        id: 6,
        itemNo: 'OSEC-DOSTTB-EXA3-1-2019',
        position: 'Executive Assistant III',
        office: 'OSEC-A',
        status: 'Contructual',
    },
    {
        id: 7,
        itemNo: 'OSEC-DOSTTB-EXA3-1-2019',
        position: 'Executive Assistant III',
        office: 'OSEC-A',
        status: 'Contructual',
    },
    {
        id: 8,
        itemNo: 'OSEC-DOSTTB-EXA3-1-2019',
        position: 'Executive Assistant III',
        office: 'OSEC-A',
        status: 'Contructual',
    },
];